### ISSUE TITLE
Doesn't work with serverless-ruby-layer

### ISSUE THREAD

**Issue by wjensen-godaddy** [godaddy/serverless-aws-servicecatalog#46]
Trying to use https://www.npmjs.com/package/serverless-ruby-layer returns the following error:
```
Serverless Error ----------------------------------------
 
  An error occurred: ApiLambdaFunctionSCProvisionedProduct - 1 validation error detected: Value 'Errors from CloudFormation: [{LogicalResourceId : SC-***-pp-3uxcvdafzv7r6, ResourceType : AWS::CloudFormation::Stack, StatusReason : The following resource(s) failed to update: [LambdaFunction]. }, {LogicalResourceId : LambdaFunction, ResourceType : AWS::Lambda::Function, StatusReason : Resource handler returned message: "1 validation error detected: Value '[[object Object]]' at 'layers' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 140, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: (arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+)|(arn:[a-zA-Z0-9-]+:lambda:::awslayer:[a-zA-Z0-9-_]+)] (Service: Lambda, Status Code: 400, Request ID: e0ddf2c5-de83-49d7-9dcc-f120225995f4, Extended Request ID: null)" (RequestToken: 7160b67f-9525-7817-8802-c0f9ce01480a, HandlerErrorCode: InvalidRequest)}, {LogicalResourceId : SC-***-pp-3uxcvdafzv7r6, ResourceType : AWS::CloudFormation::Stack, StatusReason : User Initiated}, {LogicalResourceId : SC-***-pp-3uxcvdafzv7r6, ResourceType : AWS::CloudFormation::Stack, StatusReason : User Initiated}]' at 'statusMessage' failed to satisfy constraint: Member must have length less than or equal to 1024.
```

I'm guessing it can't create the layer due to the way serverless-aws-servicecatalog works? Any way around that?

**Comment by decompil3d** [comment]
`layers` is supposed to be an array of string ARNs of exiting layers to use. From this error message, it seems like you're passing in an object of layers instead.

**Comment by wjensen-godaddy** [comment]
> layers is supposed to be an array of string ARNs 

That's what `serverless-aws-servicecatalog` expects, but I believe the framework supports it being objects? https://www.serverless.com/framework/docs/providers/aws/guide/layers 

That would explain the incompatibility I'm seeing with `serverless-ruby-layer`

**Comment by decompil3d** [comment]
The object in the framework docs is for the top-level `layers` field which tells Serverless to go create a LambdaLayer. Then, in your `function` config, you pass it the array of string ARNs of layer(s) to use. Because of our Service Catalog restrictions, Serverless is unable to create the LambdaLayer for you. Instead, you should use a `resources` section to create `CloudFormationProvisionedProduct`s that target the appropriate Service Catalog product for a layer.

**Comment by wjensen-godaddy** [comment]
Ok, that was basically my understanding. I was hoping that there was a way to create a mapping to tell Serverless: when you try to create a LambdaLayer use this CloudFormationProvisionedProduct. Since I can't stop other plugins like `serverless-ruby-layer` from trying to use the `layers` field.

**Comment by decompil3d** [comment]
That would be nice, but unfortunately it goes beyond what this plugin presently provides. You could make your own additional plugin to handle such a thing though.

**Comment by wjensen-godaddy** [comment]
I would if I knew how ^_^

But thanks for the quick response and thanks for a great plugin!
